import { ParsedNote } from "../playback/ParsedNote";

const split: ParsedNote[] = [
  // Pickup
  { note: "U", value: 0.6666667 },
  { note: "1", value: 0.6666667 },
  { note: "4", value: 6 },
  { note: "4", value: 6 },
  { note: "4", value: 6 },
  { note: "3", value: 6 },
  { note: "3", value: 6 },
  { note: "3", value: 6 },

  // 1
  { note: "1", value: 6 },
  { note: "1", value: 6 },
  { note: "2", value: 6 },
  { note: "2", value: 6 },
  { note: "1", value: 6 },
  { note: "1", value: 6 },
  { note: "2", value: 6 },
  { note: "2", value: 6 },
  { note: "1", value: 6 },
  { note: "1", value: 6 },
  { note: "2", value: 6 },
  { note: "2", value: 6 },

  { note: "1", value: 6 },
  { note: "1", value: 6 },
  { note: "2", value: 6 },
  { note: "2", value: 6 },
  { note: "3", value: 6 },
  { note: "3", value: 6 },
  { note: "1", value: 6 },
  { note: "1", value: 6 },
  { note: "2", value: 6 },
  { note: "2", value: 6 },
  { note: "3", value: 6 },
  { note: "3", value: 6 },

  // 2
  { note: "1", value: 3 },
  { note: "3", value: 6 },
  { note: "3", value: 6 },
  { note: "3", value: 3 },

  { note: "4", value: 3 },
  { note: "2", value: 6 },
  { note: "2", value: 6 },
  { note: "2", value: 3 },

  { note: "1", value: 6 },
  { note: "1", value: 6 },
  { note: "1", value: 3 },
  { note: "1", value: 3 },

  { note: "1", value: 6 },
  { note: "1", value: 6 },
  { note: "1", value: 3 },
  { note: "1", value: 3 },

  // 3
  { note: "U", value: 1.5 },
  { note: "1", value: 4.5 },
  { note: "2", value: 4.5 },
  { note: "3", value: 4.5 },
  { note: "1", value: 4.5 },
  { note: "2", value: 4.5 },
  { note: "3", value: 4.5 },

  { note: "1", value: 4.5 },
  { note: "2", value: 4.5 },
  { note: "3", value: 4.5 },
  { note: "1", value: 4.5 },
  { note: "2", value: 4.5 },
  { note: "3", value: 4.5 },
  { note: "1", value: 4.5 },
  { note: "2", value: 4.5 },
  { note: "3", value: 4.5 },

  // 4
  { note: "1", value: 6 },
  { note: "1", value: 6 },
  { note: "1", value: 6 },
  { note: "1", value: 6 },
  { note: "2", value: 6 },
  { note: "2", value: 6 },
  { note: "2", value: 6 },
  { note: "2", value: 6 },
  { note: "3", value: 6 },
  { note: "3", value: 6 },
  { note: "3", value: 6 },
  { note: "3", value: 6 },

  { note: "1", value: 8 },
  { note: "1", value: 8 },
  { note: "1", value: 8 },
  { note: "1", value: 8 },
  { note: "2", value: 8 },
  { note: "2", value: 8 },
  { note: "2", value: 8 },
  { note: "2", value: 8 },
  { note: "3", value: 8 },
  { note: "3", value: 8 },
  { note: "3", value: 8 },
  { note: "3", value: 8 },
  { note: "4", value: 8 },
  { note: "4", value: 8 },
  { note: "4", value: 8 },
  { note: "4", value: 8 },

  // 5
  { note: "3", value: 8 },
  { note: "3", value: 8 },
  { note: "3", value: 8 },
  { note: "3", value: 8 },
  { note: "2", value: 8 },
  { note: "2", value: 8 },
  { note: "2", value: 8 },
  { note: "2", value: 8 },
  { note: "1", value: 8 },
  { note: "1", value: 8 },
  { note: "1", value: 8 },
  { note: "1", value: 8 },
  { note: "2", value: 8 },
  { note: "2", value: 8 },
  { note: "2", value: 8 },
  { note: "2", value: 8 },

  { note: "1", value: 2 },
  { note: "U", value: 2 },
  { note: "U", value: 2 },
  { note: "U", value: 2 },

  // 6
  { note: "1", value: 6 },
  { note: "2", value: 6 },
  { note: "1", value: 6 },
  { note: "2", value: 6 },
  { note: "1", value: 6 },
  { note: "2", value: 6 },

  { note: "1", value: 6 },
  { note: "2", value: 6 },
  { note: "1", value: 6 },
  { note: "2", value: 6 },
  { note: "1", value: 6 },
  { note: "2", value: 6 },

  { note: "1", value: 6 },
  { note: "2", value: 6 },
  { note: "1", value: 6 },
  { note: "2", value: 6 },
  { note: "1", value: 6 },
  { note: "2", value: 6 },

  { note: "1", value: 6 },
  { note: "2", value: 6 },
  { note: "1", value: 6 },
  { note: "2", value: 6 },
  { note: "1", value: 6 },
  { note: "2", value: 6 },

  // 7
  { note: "1", value: 6 },
];

export default split;
